server:
  port: 8002
spring:
  application:
      name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   ## 注册中心eurka地址

spring:
  cloud:
    gateway:
      locator:
        enabled: true
      default-filters:
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      - id: service_to_consul
        uri: http://www.baidu.com
        order: 8000
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1
